FROM golang:1.14.4-alpine

LABEL maintainer="https://github.com/yongwoon"

ENV GO111MODULE=on
ENV GOPATH /go

RUN apk update && apk add --no-cache bash vim openssh curl gcc g++ git musl-dev \
  && go get -u -v \
  github.com/cosmtrek/air \
  github.com/smartystreets/goconvey \
  golang.org/x/tools/gopls@latest \
  github.com/ramya-rao-a/go-outline \
  github.com/rogpeppe/godef \
  golang.org/x/tools/cmd/goimports \
  golang.org/x/lint/golint \
  && GO111MODULE=off go get -v \
  github.com/rubenv/sql-migrate/... \
  github.com/go-delve/delve/cmd/dlv

WORKDIR /go/src/github.com/yongwoon/echo-blog

COPY . .

RUN go mod download

# CMD air -c .air.conf
