FROM golang:1.14.4-alpine

LABEL maintainer="https://github.com/yongwoon"

ENV GO111MODULE=on
ENV GOPATH /go

RUN apk update && apk add --no-cache bash vim openssh curl gcc g++ git musl-dev \
  && go get github.com/cosmtrek/air \
  && GO111MODULE=off go get -v github.com/rubenv/sql-migrate/...

WORKDIR /go/src/github.com/yongwoon/echo-blog

COPY . .

RUN go mod download
