default: &default
  dialect: mysql
  datasource: ${DATABASE_USER}:${DATABASE_PASSWORD}@tcp(${DATABASE_HOST}:${DATABASE_PORT})/${DATABASE_SCHEMA}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
  dir: db/migration

development:
  <<: *default

test:
  <<: *default
  datasource: ${DATABASE_USER}:${DATABASE_PASSWORD}@tcp(${DATABASE_HOST}:${DATABASE_PORT})/echo_blog_test?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
  <<: *default
